### ISSUE TITLE
C #include missing

### ISSUE THREAD

**Issue by alorma** [PDDStudio/highlightjs-android#3] opened 2016-07-03 16:00 UTC
Related to: https://github.com/gitskarios/Gitskarios/issues/476

![](https://camo.githubusercontent.com/9095aebae7fe4c289f9236a3954487afdb35d368/687474703a2f2f692e696d6775722e636f6d2f736938347855552e706e67)

![](https://camo.githubusercontent.com/ef8d006c776d988e740d30beed80b9d564dfdcc1/687474703a2f2f692e696d6775722e636f6d2f306e4f44396f502e706e67)

**Comment by PDDStudio** [comment] 2016-07-05 15:05
Thanks for reporting. I've to debug the source to see whether this problem is caused by the library or by Highlight.JS

**Comment by PDDStudio** [comment] 2016-07-06 07:35
I was able to reproduce this issue. It seems like this parsing error is caused by HighlightJs itself and not the library. I file an issue on their repository.

**Comment by alorma** [comment] 2016-07-06 10:33
:+1:

**Comment by PDDStudio** [comment] 2016-07-12 13:53
Should be fixed with [Version 1.2.0](https://github.com/PDDStudio/highlightjs-android/releases/tag/1.2.0)

**Closed as completed by PDDStudio** 2016-07-12 13:53 UTC
Labels: bug
