### ISSUE TITLE
Diff colored

### ISSUE THREAD

**Issue by alorma** [PDDStudio/highlightjs-android#6] opened 2016-09-06 09:52 UTC
Hi.

https://github.com/gitskarios/Gitskarios/issues/560

HighlightJsView doesn't show diff lines in green / red

**Comment by PDDStudio** [comment] 2016-09-15 20:46
Thanks for reporting @alorma
Sorry for my late reply on this issue. Are both parts using HighlightJsView?
Can you please also provide a snippet/file to reproduce this issue? And which library version are you using?

**Comment by PDDStudio** [comment] 2017-03-25 02:09
I'm closing this for now as because I wasn't able to get the required information to debug this further. In case there's any need for this feel free to file a new issue with proper details.

**Closed as completed by PDDStudio** 2017-03-25 02:09 UTC
